#! /bin/sh

xrandr --output HDMI-2 --mode 1920x1080 --rate 74.97 &
feh --bg-scale $HOME/Pictures/hellofriend.png &
$HOME/.config/polybar/launch.sh &
setxkbmap -option grp:alt_shift_toggle us,ru &
numlockx on &
dunst &
warpd &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a firefox desktop='^9'
bspc rule -a discord desktop='^6'
